### ISSUE TITLE
Review of Templates for Cassandra

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#139]
Rename of the default template as part of transition to Cassandra 3.

This has now been extended as a review of all configurations of 2.0, 2.1 and 2.2 which will replace the far too generic version 2 template that is present at the moment.  This should be done before any work on version 3 as it be used as the method of going forward.

**Comment by dallinb** [comment]
Not really sure where to go with this. I was pretty sure I saw DSE 4.6 not like the default template, but just did a trial run with DSC 2.0 and was unable to duplicate the problem.

**Comment by dallinb** [comment]
When attempting to install Cassandra 2.0.17 on CentOS 7, get the following error:

```
Invalid yaml. Please remove properties [concurrent_counter_writes, index_summary_capacity_in_mb, counter_write_request_timeout_in_ms, memtable_allocation_type, counter_cache_save_period, sstable_preemptive_open_interval_in_mb, counter_cache_size_in_mb, index_summary_resize_interval_in_minutes] from your cassandra.yaml
```

**Comment by dallinb** [comment]
```
  ERROR [main] 2016-03-03 14:34:42,788 DatabaseDescriptor.java (line 117) Fatal configuration error
  org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml. Please remove properties [rpc_interface, listen_interface] from your cassandra.yaml
  	at org.apache.cassandra.config.YamlConfigurationLoader$MissingPropertiesChecker.check(YamlConfigurationLoader.java:137)
  	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:100)
  	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:73)
  	at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:136)
  	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:112)
  	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:213)
  	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:554)
  	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:643)
```
