### ISSUE TITLE
Beaker Tests Failing for All OS Distros

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#169]
Delaying release [v.1.13.0](#168) (see https://travis-ci.org/locp/cassandra/builds/109124667). Also failed when releasing [v.1.12.2]( #167) (see https://travis-ci.org/locp/cassandra/builds/108732829).  The last successful build was [v1.12.1](#164) (see https://travis-ci.org/locp/cassandra/builds/107859827) which happened on February 8th.

Getting the following message:

```
/home/ec2-user/.rvm/gems/ruby-2.2.1/gems/beaker-2.34.0/lib/beaker/dsl/helpers/host_helpers.rb:76:in `block in on': DSL method `on` can only be called with a String or Beaker::Command object as the command parameter, not NilClass. (ArgumentError)
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/beaker-2.34.0/lib/beaker/shared/host_manager.rb:115:in `run_block_on'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/beaker-2.34.0/lib/beaker/dsl/patterns.rb:35:in `block_on'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/beaker-2.34.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
	from /home/ec2-user/workspace/spec/spec_helper_acceptance.rb:6:in `block in <top (required)>'
	from /home/ec2-user/workspace/spec/spec_helper_acceptance.rb:4:in `each'
	from /home/ec2-user/workspace/spec/spec_helper_acceptance.rb:4:in `<top (required)>'
	from /home/ec2-user/workspace/spec/acceptance/cassandra_spec.rb:1:in `require'
	from /home/ec2-user/workspace/spec/acceptance/cassandra_spec.rb:1:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1361:in `load'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `each'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:106:in `setup'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/exe/rspec:4:in `<main>'
/home/ec2-user/.rvm/rubies/ruby-2.2.1/bin/ruby -I/home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/lib:/home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-support-3.4.1/lib /home/ec2-user/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.2/exe/rspec spec/acceptance --color failed
```

This is happening on AWS and on local nodes.  I have only updated my Gem bundle today which gave me the following updates:

* backports 3.6.8
* beaker 2.34.0
* beaker-answers 0.4.0
* google-api-client 0.9.2
* serverspec 2.29.2
* specinfra 2.51.1

**Comment by dallinb** [comment]
The time in question is a change to the environment (possibly by a third-party) between February 8th (when we had a successful build) and February 12th when we started having problems with v.1.12.2.

**Suspect Gems**

* backports-3.6.8 February 9, 2016
* beaker-2.34.0 February 10, 2016
* beaker-answers-0.4.0 February 12, 2016
* google-api-client-0.9.2 February 10, 2016
* serverspec-2.29.2 February 9, 2016
