### ISSUE TITLE
Facter variables have stopped working

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#382]
Need to investigate when this happened and what caused it, but the facter variables provided by the module are no longer working.  Discovered on Docker but also happening on vagrant so assuming it is universal.

**Comment by dallinb** [comment]
This seems to get them back into a cache:

```bash
# puppet facts find facts
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
{"name":"facts","values":{"path":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","kernel":"Linux","facterversion":"2.4.6","architecture":"amd64","lsbdistid":"Debian","ps":"ps -ef","osfamily":"Debian","blockdevice_sda_size":"256060514304","blockdevice_sda_vendor":"ATA","blockdevice_sda_model":"TOSHIBA THNSNJ25","blockdevices":"sda","rubyplatform":"x86_64-linux","os":"{\"name\"=>\"Debian\", \"family\"=>\"Debian\", \"release\"=>{\"major\"=>\"7\", \"minor\"=>\"11\", \"full\"=>\"7.11\"}, \"lsb\"=>{\"distcodename\"=>\"wheezy\", \"distid\"=>\"Debian\", \"distdescription\"=>\"Debian GNU/Linux 7.11 (wheezy)\", \"distrelease\"=>\"7.11\", \"majdistrelease\"=>\"7\", \"minordistrelease\"=>\"11\"}}","lsbdistrelease":"7.11","lsbdistdescription":"Debian GNU/Linux 7.11 (wheezy)","operatingsystem":"Debian","selinux":"false","virtual":"docker","is_virtual":"true","partitions":"{\"sda1\"=>{\"size\"=>\"1048576\", \"filesystem\"=>\"vfat\"}, \"sda2\"=>{\"size\"=>\"499712\", \"filesystem\"=>\"ext2\"}, \"sda3\"=>{\"size\"=>\"498567168\", \"filesystem\"=>\"crypto_LUKS\"}}","filesystems":"ext2,ext3,ext4,squashfs,vfat","interfaces":"","ipaddress":"172.17.0.2","fqdn":"debian7.default","system_uptime":"{\"seconds\"=>13904, \"hours\"=>3, \"days\"=>0, \"uptime\"=>\"3:51 hours\"}","lsbminordistrelease":"11","operatingsystemmajrelease":"7","lsbmajdistrelease":"7","hardwaremodel":"x86_64","domain":"default","augeasversion":"0.10.0","kernelversion":"4.4.0","lsbdistcodename":"wheezy","gid":"root","boardmanufacturer":"FF50","boardproductname":"06F3","boardserialnumber":"QC1G0RAF3801967","bios_vendor":"INSYDE Corp.","bios_version":"1.10","bios_release_date":"08/18/2015","manufacturer":"TOSHIBA","productname":"SATELLITE P50-C","serialnumber":"9F209929C","uuid":"CE5AC645-BE91-C241-9A1D-0A0CCF96E9CB","type":"Notebook","uptime":"3:51 hours","uptime_days":"0","hostname":"debian7","kernelrelease":"4.4.0-72-generic","operatingsystemrelease":"7.11","uniqueid":"11ac0200","timezone":"UTC","uptime_seconds":"13904","uptime_hours":"3","kernelmajversion":"4.4","puppetversion":"3.8.7","physicalprocessorcount":"1","memorysize":"15.51 GB","memoryfree":"8.56 GB","swapsize":"0.00 MB","swapfree":"0.00 MB","swapsize_mb":"0.00","swapfree_mb":"0.00","memorysize_mb":"15881.84","memoryfree_mb":"8761.30","rubysitedir":"/usr/local/lib/site_ruby/1.9.1","hardwareisa":"unknown","processors":"{\"models\"=>[\"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz\", \"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz\", \"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz\", \"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz\"], \"count\"=>4, \"physicalcount\"=>1}","processor0":"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz","processor1":"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz","processor2":"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz","processor3":"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz","processorcount":"4","rubyversion":"1.9.3","id":"root","sshdsakey":"AAAAB3NzaC1kc3MAAACBAPIq2FfoIndhpwlh2SP1g3k004VbHv1xTAwT13uiaqkB8N0jIQaeNA2sVkqbXjBzg+H9yeS8XdKwUUh3daAkI12bozVslYqy72p7LGCrRKr9L8hEe91h/9vgDgFMk7UUdAZHjAtIco6xEx7brQY9rgBahNC4DJ2eVufNviKgaB5hAAAAFQD6rdN1bfnIEjZQ8aC1Z+gpNnAX3wAAAIEA0RYhBS6Fo/8AAA2s0ZxuyGVd/ekHMIJZ1yYRjRcED2WcXm9ebM6HEgcmVMAwuk2O4W8XUoSwyAZbzBAkxU2H/8ALZXTBClNKss6jDwVAwCh2/F/SLWhszq5BGSXjt6XegK9RqIexEcGjRcB2gUaUNq0cd7Xj6KIjp4GyFLwen60AAACBAIxWpRNWMxwGJByEbEpG1w69jm5GS8TZkuksqDz1LHTOVM9XJjYewZ0aHSt5tGHYYU742a22IpphDsuGZ0cBc+FBL4oZJcUSy3oIYh2z422MHcqOrXtJ/ocf9yWJg98LPEoHlgpkFlPnzWBm9cnMN0YAdfPpFv714Nar/ZLe7Nwq","sshfp_dsa":"SSHFP 2 1 ad19b460e139bb4c80db761460886f80fde152ed\nSSHFP 2 2 30c53e72e42aad3e9c2cad3da6eb04b2e9bbb628b9fda5f15c5631c7cf5f2e75","sshrsakey":"AAAAB3NzaC1yc2EAAAADAQABAAABAQDLT7ZdF0bFl/mKusab07d5l5WggkETcvizHzC3pa6VUcwlTjZFcvtEn9Z7OI8ebncHOjM3vaWQbnikr9eJURHbH8EY9k443529LEQw8tpoyjS+LcYV7/hnFqPU9X3zcIPlfX+ATE4PMG7L255OO6Qeui3XzAGvWJAxwLVnNKJNW8Cujzof9z1nUisOxU6YKBOxXW105mttFvCMQ8gZPt48OTCvQaLhb/Kc4qrIgar7JkZaCgZbM4yWS5JKy3Qdexshi037fVa4C4J7QKhOO0JQ0yQMMTXBgAoxQE4F3YFPKMb2PzhZttpm7W2FcbqGH6Hw+b9qeLpPXJhils9D1UdN","sshfp_rsa":"SSHFP 1 1 32ca130b1779cff503343e08f40a801de5192a52\nSSHFP 1 2 caa3ce4dcf8dc356be35607cd6657d45738a7a91f6e918fca64068ac46fbea35","sshecdsakey":"AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGsRxogHqsnDlAkC6/hYoJUil1v1MUOMSMNWtC2zNlvzDNlU/Z5TudL+8nn+cFL6INiHifw3DSuAYr6aoAFy3c8=","sshfp_ecdsa":"SSHFP 3 1 ea44e15f8d649de33310d56c83f9633f846559f2\nSSHFP 3 2 2bcfdf3d6ecb88b6e4d70669ee58d2c46c280efd9036c68b451a26e6b4dd572d","ip6tables_version":"1.4.14","iptables_version":"1.4.14","apt_reboot_required":"false","apt_update_last_success":"1492938185","apt_has_updates":"false","cassandramaxheapsize":"3970","cassandramajorversion":"2","cassandracmsheapnewsize":"400","cassandraminorversion":"1","cassandrarelease":"2.1.17","cassandrapatchversion":"17","cassandracmsmaxheapsize":"3970","cassandraheapnewsize":"400","root_home":"/root","service_provider":"debian","is_pe":"false","puppet_vardir":"/var/lib/puppet","puppet_environmentpath":"","puppet_server":"puppet","package_provider":"apt","clientcert":"debian7.default","clientversion":"3.8.7","clientnoop":"false"},"timestamp":"2017-04-23 09:04:21 +0000","expiration":"2017-04-23T09:34:21.076432024+00:00"}
```

Followed by:
```bash
# puppet apply -e 'notify{ "${::cassandrarelease}": }'
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
Notice: Compiled catalog for debian7.default in environment production in 0.01 seconds
Notice: 2.2.9
Notice: /Stage[main]/Main/Notify[2.2.9]/message: defined 'message' as '2.2.9'
Notice: Finished catalog run in 0.04 seconds
```
