### ISSUE TITLE
CASSANDRA-9822- Cassandra Service Status Problems

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#63]
See https://issues.apache.org/jira/browse/CASSANDRA-9822

Ubuntu installs OK but can't get the status of the service.  `spec beaker` shows the following:

```
cassandra class
  Initial install.
localhost $ scp /tmp/beaker20150725-32375-ej35h0 ubuntu-server-1404-x64:/tmp/apply_manifest.pp.b1aUpI {:ignore => }
    should work with no errors
  Idempotency test.
localhost $ scp /tmp/beaker20150725-32375-144baon ubuntu-server-1404-x64:/tmp/apply_manifest.pp.nVmxXV {:ignore => }
    should work with no errors (FAILED - 1)
  Service "cassandra"
    should be running
    should be enabled
  Service "datastax-agent"
    should be running
    should be enabled
  Service "opscenterd"
    should be running
    should be enabled

Failures:

  1) cassandra class Idempotency test. should work with no errors
     Failure/Error: expect(apply_manifest(idempotency_pp, :catch_failures => true).exit_code).to be_zero
       expected `2.zero?` to return true, got false
     # ./spec/acceptance/cassandra_spec.rb:37:in `block (3 levels) in <top (required)>'

Finished in 8 minutes 49 seconds (files took 3 minutes 23.4 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/acceptance/cassandra_spec.rb:36 # cassandra class Idempotency test. should work with no errors
```
All is running OK, but status shows the following:

```bash
# service cassandra status
 * could not access pidfile for Cassandra
```

Does not affect CentOS.

**Comment by dallinb** [comment]
Just ran a regress test on 0.4.3 which had passed it's tests perfectly before it's release.  It is also now failing.  Possibly this is an issue on Debian systems since Cassandra 2.2 was released.  Get the following log:

```
/home/dallinb/.rvm/rubies/ruby-2.0.0-p643/bin/ruby -I/home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.1/lib:/home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/rspec-support-3.3.0/lib /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.1/exe/rspec spec/acceptance --color
/home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-rspec-5.1.0/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/specinfra-2.37.5/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Beaker::Hypervisor, found some vagrant boxes to create
Bringing machine 'ubuntu-server-1204-x64' up with 'virtualbox' provider...
==> ubuntu-server-1204-x64: Importing base box 'puppetlabs/ubuntu-12.04-64-nocm'...
==> ubuntu-server-1204-x64: Matching MAC address for NAT networking...
==> ubuntu-server-1204-x64: Checking if box 'puppetlabs/ubuntu-12.04-64-nocm' is up to date...
==> ubuntu-server-1204-x64: Setting the name of the VM: ubuntu-server-1204-x64yml_ubuntu-server-1204-x64_1437855383789_21956
==> ubuntu-server-1204-x64: Clearing any previously set network interfaces...
==> ubuntu-server-1204-x64: Preparing network interfaces based on configuration...
    ubuntu-server-1204-x64: Adapter 1: nat
    ubuntu-server-1204-x64: Adapter 2: hostonly
==> ubuntu-server-1204-x64: Forwarding ports...
    ubuntu-server-1204-x64: 22 => 2222 (adapter 1)
==> ubuntu-server-1204-x64: Running 'pre-boot' VM customizations...
==> ubuntu-server-1204-x64: Booting VM...
==> ubuntu-server-1204-x64: Waiting for machine to boot. This may take a few minutes...
    ubuntu-server-1204-x64: SSH address: 127.0.0.1:2222
    ubuntu-server-1204-x64: SSH username: vagrant
    ubuntu-server-1204-x64: SSH auth method: private key
    ubuntu-server-1204-x64: Warning: Connection timeout. Retrying...
==> ubuntu-server-1204-x64: Machine booted and ready!
==> ubuntu-server-1204-x64: Checking for guest additions in VM...
==> ubuntu-server-1204-x64: Setting hostname...
==> ubuntu-server-1204-x64: Configuring and enabling network interfaces...
==> ubuntu-server-1204-x64: Mounting shared folders...
    ubuntu-server-1204-x64: /vagrant => /home/dallinb/locp-cassandra/v0.4.3/.vagrant/beaker_vagrant_files/ubuntu-server-1204-x64.yml
Warning: ssh connection to 10.255.57.237 has been terminated
Warning: ssh connection to 10.255.57.237 has been terminated
localhost $ scp /home/dallinb/locp-cassandra/v0.4.3 ubuntu-server-1204-x64:/etc/puppet/modules {:ignore => [".bundle", ".git", ".idea", ".vagrant", ".vendor", "vendor", "acceptance", "bundle", "spec", "tests", "log", ".", ".."]}

cassandra class
  Install Cassandra with Java.
localhost $ scp /tmp/beaker20150725-8618-1efhsu7 ubuntu-server-1204-x64:/tmp/apply_manifest.pp.cwX7Vb {:ignore => }
    should work with no errors (FAILED - 1)
  Install the Optional Cassandra tools.
localhost $ scp /tmp/beaker20150725-8618-im5w63 ubuntu-server-1204-x64:/tmp/apply_manifest.pp.7AtaSl {:ignore => }
    should work with no errors (FAILED - 2)
  Install the DataStax Agent.
localhost $ scp /tmp/beaker20150725-8618-1xmsh67 ubuntu-server-1204-x64:/tmp/apply_manifest.pp.uF4lny {:ignore => }
    should work with no errors (FAILED - 3)
  Idempotency test.
localhost $ scp /tmp/beaker20150725-8618-1lx6oy ubuntu-server-1204-x64:/tmp/apply_manifest.pp.LxNsiP {:ignore => }
    should work with no errors (FAILED - 4)
  Service "cassandra"
    should be running (FAILED - 5)
    should be enabled (FAILED - 6)
  Service "datastax-agent"
    should be running (FAILED - 7)
    should be enabled (FAILED - 8)

Failures:

  1) cassandra class Install Cassandra with Java. should work with no errors
     Failure/Error: apply_manifest(pp1, :catch_failures => true)
     Beaker::Host::CommandFailure:
       Host 'ubuntu-server-1204-x64' exited with 6 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.cwX7Vb
       Last 10 lines of output were:
       	
       	The following packages have unmet dependencies:
       	 dsc21 : Depends: cassandra (= 2.1.8) but 2.2.0 is to be installed
       	E: Unable to correct problems, you have held broken packages.
       	Notice: /Stage[main]/Cassandra/File[/etc/cassandra/cassandra.yaml]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra/File[/etc/cassandra/cassandra.yaml]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra/Service[cassandra]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra/Service[cassandra]: Skipping because of failed dependencies
       	Info: Creating state file /var/lib/puppet/state/state.yaml
       	Notice: Finished catalog run in 92.34 seconds
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/host.rb:273:in `exec'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:73:in `block in on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:457:in `block in apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:386:in `apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:464:in `apply_manifest'
     # ./spec/acceptance/cassandra_spec.rb:14:in `block (3 levels) in <top (required)>'

  2) cassandra class Install the Optional Cassandra tools. should work with no errors
     Failure/Error: apply_manifest(pp2, :catch_failures => true)
     Beaker::Host::CommandFailure:
       Host 'ubuntu-server-1204-x64' exited with 4 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.7AtaSl
       Last 10 lines of output were:
       	The following packages have unmet dependencies:
       	 dsc21 : Depends: cassandra (= 2.1.8) but 2.2.0 is to be installed
       	E: Unable to correct problems, you have held broken packages.
       	Notice: /Stage[main]/Cassandra/File[/etc/cassandra/cassandra.yaml]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra/File[/etc/cassandra/cassandra.yaml]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra/Service[cassandra]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra/Service[cassandra]: Skipping because of failed dependencies
       	Notice: /Package[cassandra-tools]: Dependency Package[dsc21] has failures: true
       	Warning: /Package[cassandra-tools]: Skipping because of failed dependencies
       	Notice: Finished catalog run in 1.93 seconds
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/host.rb:273:in `exec'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:73:in `block in on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:457:in `block in apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:386:in `apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:464:in `apply_manifest'
     # ./spec/acceptance/cassandra_spec.rb:25:in `block (3 levels) in <top (required)>'

  3) cassandra class Install the DataStax Agent. should work with no errors
     Failure/Error: apply_manifest(pp3, :catch_failures => true)
     Beaker::Host::CommandFailure:
       Host 'ubuntu-server-1204-x64' exited with 4 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.uF4lny
       Last 10 lines of output were:
       	Warning: /Stage[main]/Cassandra/File[/etc/cassandra/cassandra.yaml]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra/Service[cassandra]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra/Service[cassandra]: Skipping because of failed dependencies
       	Notice: /Package[datastax-agent]: Dependency Package[dsc21] has failures: true
       	Warning: /Package[datastax-agent]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra::Datastax_agent/Ini_setting[stomp_interface]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra::Datastax_agent/Ini_setting[stomp_interface]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra::Datastax_agent/Service[datastax-agent]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra::Datastax_agent/Service[datastax-agent]: Skipping because of failed dependencies
       	Notice: Finished catalog run in 2.16 seconds
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/host.rb:273:in `exec'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:73:in `block in on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:457:in `block in apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:386:in `apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:464:in `apply_manifest'
     # ./spec/acceptance/cassandra_spec.rb:36:in `block (3 levels) in <top (required)>'

  4) cassandra class Idempotency test. should work with no errors
     Failure/Error: expect(apply_manifest(pp3, :catch_failures => true).exit_code).to be_zero
     Beaker::Host::CommandFailure:
       Host 'ubuntu-server-1204-x64' exited with 4 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.LxNsiP
       Last 10 lines of output were:
       	Warning: /Stage[main]/Cassandra/File[/etc/cassandra/cassandra.yaml]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra/Service[cassandra]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra/Service[cassandra]: Skipping because of failed dependencies
       	Notice: /Package[datastax-agent]: Dependency Package[dsc21] has failures: true
       	Warning: /Package[datastax-agent]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra::Datastax_agent/Ini_setting[stomp_interface]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra::Datastax_agent/Ini_setting[stomp_interface]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra::Datastax_agent/Service[datastax-agent]: Dependency Package[dsc21] has failures: true
       	Warning: /Stage[main]/Cassandra::Datastax_agent/Service[datastax-agent]: Skipping because of failed dependencies
       	Notice: Finished catalog run in 2.15 seconds
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/host.rb:273:in `exec'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:73:in `block in on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:457:in `block in apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:386:in `apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.1/lib/beaker/dsl/helpers/puppet_helpers.rb:464:in `apply_manifest'
     # ./spec/acceptance/cassandra_spec.rb:53:in `block (3 levels) in <top (required)>'

  5) cassandra class Service "cassandra" should be running
     Failure/Error: it { is_expected.to be_running }
       expected Service "cassandra" to be running
     # ./spec/acceptance/cassandra_spec.rb:58:in `block (3 levels) in <top (required)>'

  6) cassandra class Service "cassandra" should be enabled
     Failure/Error: it { is_expected.to be_enabled }
       expected Service "cassandra" to be enabled
     # ./spec/acceptance/cassandra_spec.rb:59:in `block (3 levels) in <top (required)>'

  7) cassandra class Service "datastax-agent" should be running
     Failure/Error: it { is_expected.to be_running }
       expected Service "datastax-agent" to be running
     # ./spec/acceptance/cassandra_spec.rb:63:in `block (3 levels) in <top (required)>'

  8) cassandra class Service "datastax-agent" should be enabled
     Failure/Error: it { is_expected.to be_enabled }
       expected Service "datastax-agent" to be enabled
     # ./spec/acceptance/cassandra_spec.rb:64:in `block (3 levels) in <top (required)>'

Finished in 2 minutes 10 seconds (files took 2 minutes 14.8 seconds to load)
8 examples, 8 failures

Failed examples:

rspec ./spec/acceptance/cassandra_spec.rb:13 # cassandra class Install Cassandra with Java. should work with no errors
rspec ./spec/acceptance/cassandra_spec.rb:24 # cassandra class Install the Optional Cassandra tools. should work with no errors
rspec ./spec/acceptance/cassandra_spec.rb:35 # cassandra class Install the DataStax Agent. should work with no errors
rspec ./spec/acceptance/cassandra_spec.rb:52 # cassandra class Idempotency test. should work with no errors
rspec ./spec/acceptance/cassandra_spec.rb:58 # cassandra class Service "cassandra" should be running
rspec ./spec/acceptance/cassandra_spec.rb:59 # cassandra class Service "cassandra" should be enabled
rspec ./spec/acceptance/cassandra_spec.rb:63 # cassandra class Service "datastax-agent" should be running
rspec ./spec/acceptance/cassandra_spec.rb:64 # cassandra class Service "datastax-agent" should be enabled
```

**Comment by dallinb** [comment]
Seems to be related to https://issues.apache.org/jira/browse/CASSANDRA-9822

**Comment by eyaget** [comment]
Cassandra 2.2 is not working on ubuntu 14.04.1. Sudo service cassandra returns "could not access pid file for cassandra". Please lets know if there is a fix for this. Thanks.

**Comment by dallinb** [comment]
Hi,

The problem is with the Cassandra distribution on Ubuntu, not with the Puppet module.  The link to the Cassandra problem report is https://issues.apache.org/jira/browse/CASSANDRA-9822 where the issues was reported on the 15th of this month.  Unfortunately it does not seem to have had any updates since that day.

The options are:

1. Leave it as it is and wait for Cassandra to fix their distribution.  This may take time and during
    the wait Ubuntu users will experience this problem.
2. Fix the distributed */etc/init.d/cassandra* (perhaps with an optional flag) and deploy that as part
    of the Puppet module.  While this seems to be doing DataStax's job for them, it would get Ubuntu
    users of this module out of the hole now.

Let me know if you would find the second option useful and if so I will start working on it.

Best wishes,

Ben

**Comment by eyaget** [comment]
Thank you very much for the prompt reply Dallinb!. Hope they will fix it ASAP.

**Comment by dallinb** [comment]
Hi Eyasu,

I've thought about this a bit more.  How about we have a parameter on the Cassandra class called cassandra_9822 with a default value of false.  If it is set to true, it will drop in a working init script.  This will only have any effect on Ubuntu systems.

What do you think?

Ben

**Comment by eyaget** [comment]
Hi Ben,

Thanks for the suggestion. Actually am not working on Cassandra, i.e., am neither developer nor contributor on cassandra project. I have been just using cassandra database for my project. Hence, I am not able to change and build the source code of Cassandra. I can't able to use it unless otherwise it gets solved by someone else or the cassandra community themselves :). But am really eagerly waiting this fix as I am stuck on the middle of my project due to this problem. 

Any suggestion?

Eyasu.

**Comment by dallinb** [comment]
Hi Eyasu,

I'll try and get a workaround this evening and will post details here and get a patch to the Puppet module.

Regards,

Ben

**Comment by eyaget** [comment]
Thanks again Ben!. Please try if you can able to get a workaround and update us. I can't wait to hear the news :).

**Comment by dallinb** [comment]
In the file **/etc/init.d/cassandra** change line 60 from:

```shell
CMD_PATT="cassandra.+CassandraDaemon"
```

to:

```shell
CMD_PATT="cassandra"
```

This can also be achieved with version 1.0.1 of the locp-cassandra module using the following parameter:

```puppet
class { 'cassandra':
  cassandra_9822  => true
}
```

When used with the **cassandra_9822** parameter, Ubuntu tests become idempotent again.  This is because the command ```service cassandra status``` returns correctly.

**Comment by dallinb** [comment]
Eyasu,

Please can you confirm if this fixes your problem?

Best wishes,

Ben

**Comment by eyaget** [comment]
Hi Ben,

Thank you very much for the fix!. Indeed it solves the problem. Good job :)

**Comment by dallinb** [comment]
Eyasu,

Glad to hear it!  If you could fill out the Puppet Forge survey for the module at https://forge.puppetlabs.com/locp/cassandra it would be greatly appreciated.  Please also raise any suggestions of features or improvements here or at the Gitter chat page at https://gitter.im/locp/cassandra which can be accessed with your Git Hub credentials.

Best wishes,

Ben

**Comment by eyaget** [comment]
Ben,

Sure, I'll definitely do that. Thanks again. However, the same problem has happened on the other project of me that uses cassandra. It never happened before. Structure of the other project is also quite similar to cassandra. Asking help on that will be off the topic. Can we please have a private chat? my gmail is eya.get@gmail.com, please contact me on gmail or let me know your contact address. Thanks once again!.
