### ISSUE TITLE
Acceptance tests (Beaker) are failing.

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#79]
CentOS tests are working fine, but Ubuntu tests seem to have problems (despite all services running fine).
```
Beaker::Hypervisor, found some vagrant boxes to create
Bringing machine 'ubuntu-server-1204-x64' up with 'virtualbox' provider...
==> ubuntu-server-1204-x64: Importing base box 'puppetlabs/ubuntu-12.04-64-nocm'...
==> ubuntu-server-1204-x64: Matching MAC address for NAT networking...
==> ubuntu-server-1204-x64: Checking if box 'puppetlabs/ubuntu-12.04-64-nocm' is up to date...
==> ubuntu-server-1204-x64: Setting the name of the VM: ubuntu-server-1204-x64yml_ubuntu-server-1204-x64_1439967982220_37316
==> ubuntu-server-1204-x64: Clearing any previously set network interfaces...
==> ubuntu-server-1204-x64: Preparing network interfaces based on configuration...
    ubuntu-server-1204-x64: Adapter 1: nat
    ubuntu-server-1204-x64: Adapter 2: hostonly
==> ubuntu-server-1204-x64: Forwarding ports...
    ubuntu-server-1204-x64: 22 => 2222 (adapter 1)
==> ubuntu-server-1204-x64: Running 'pre-boot' VM customizations...
==> ubuntu-server-1204-x64: Booting VM...
==> ubuntu-server-1204-x64: Waiting for machine to boot. This may take a few minutes...
    ubuntu-server-1204-x64: SSH address: 127.0.0.1:2222
    ubuntu-server-1204-x64: SSH username: vagrant
    ubuntu-server-1204-x64: SSH auth method: private key
    ubuntu-server-1204-x64: Warning: Connection timeout. Retrying...
==> ubuntu-server-1204-x64: Machine booted and ready!
GuestAdditions 4.3.22 running --- OK.
==> ubuntu-server-1204-x64: Checking for guest additions in VM...
==> ubuntu-server-1204-x64: Setting hostname...
==> ubuntu-server-1204-x64: Configuring and enabling network interfaces...
==> ubuntu-server-1204-x64: Mounting shared folders...
    ubuntu-server-1204-x64: /vagrant => /home/dallinb/locp-cassandra/v1.3.0/.vagrant/beaker_vagrant_files/ubuntu-server-1204-x64.yml
Warning: ssh connection to 10.255.128.126 has been terminated
Warning: ssh connection to 10.255.128.126 has been terminated
localhost $ scp /home/dallinb/locp-cassandra/v1.3.0 ubuntu-server-1204-x64:/etc/puppet/modules {:ignore => [".bundle", ".git", ".idea", ".vagrant", ".vendor", "vendor", "acceptance", "bundle", "spec", "tests", "log", ".", ".."]}

cassandra class
  Initial install.
localhost $ scp /tmp/beaker20150819-26659-16i6i4s ubuntu-server-1204-x64:/tmp/apply_manifest.pp.CpYbV7 {:ignore => }
    should work with no errors (FAILED - 1)
  Idempotency test.
localhost $ scp /tmp/beaker20150819-26659-gdjrfz ubuntu-server-1204-x64:/tmp/apply_manifest.pp.meawwN {:ignore => }
    should work with no errors (FAILED - 2)
  Service "cassandra"
    should be running
    should be enabled
  Service "datastax-agent"
    should be running
    should be enabled
  Service "opscenterd"
    should be running
    should be enabled

Failures:

  1) cassandra class Initial install. should work with no errors
     Failure/Error: apply_manifest(cassandra_pp, :catch_failures => true)
     Beaker::Host::CommandFailure:
       Host 'ubuntu-server-1204-x64' exited with 6 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.CpYbV7
       Last 10 lines of output were:
       	Notice: /Stage[main]/Cassandra::Opscenter/Cassandra::Opscenter::Setting[agents tmp_dir]/Ini_setting[agents tmp_dir]: Dependency Package[opscenter] has failures: true
       	Warning: /Stage[main]/Cassandra::Opscenter/Cassandra::Opscenter::Setting[ Dependency Package[opscenter] has failures: true
       	Warning: /Stage[main]/Cassandra::Opscenter/Cassandra::Opscenter::Setting[webserver tarball_process_timeout]/Ini_setting[webserver tarball_process_timeout]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra::Opscenter/Cassandra::Opscenter::Setting[agents incoming_port]/Ini_setting[agents incoming_port]: Dependency Package[opscenter] has failures: true
       	Warning: /Stage[main]/Cassandra::Opscenter/Cassandra::Opscenter::Setting[agents incoming_port]/Ini_setting[agents incoming_port]: Skipping because of failed dependencies
       	Notice: /Stage[main]/Cassandra::Opscenter/Service[opscenterd]: Dependency Package[opscenter] has failures: true
       	Warning: /Stage[main]/Cassandra::Opscenter/Service[opscenterd]: Skipping because of failed dependencies
       	Info: Creating state file /var/lib/puppet/state/state.yaml
       	Notice: Finished catalog run in 490.99 seconds
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/host.rb:281:in `exec'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/dsl/helpers/host_helpers.rb:73:in `block in on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/dsl/helpers/puppet_helpers.rb:457:in `block in apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/shared/host_manager.rb:104:in `run_block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/dsl/helpers/puppet_helpers.rb:386:in `apply_manifest_on'
     # /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/beaker-2.18.3/lib/beaker/dsl/helpers/puppet_helpers.rb:464:in `apply_manifest'
     # ./spec/acceptance/cassandra_spec.rb:26:in `block (3 levels) in <top (required)>'

  2) cassandra class Idempotency test. should work with no errors
     Failure/Error: expect(apply_manifest(idempotency_pp, :catch_failures => true).exit_code).to be_zero
       expected `2.zero?` to return true, got false
     # ./spec/acceptance/cassandra_spec.rb:52:in `block (3 levels) in <top (required)>'

Finished in 15 minutes 19 seconds (files took 2 minutes 42.1 seconds to load)
8 examples, 2 failures

Failed examples:

rspec ./spec/acceptance/cassandra_spec.rb:25 # cassandra class Initial install. should work with no errors
rspec ./spec/acceptance/cassandra_spec.rb:51 # cassandra class Idempotency test. should work with no errors

/home/dallinb/.rvm/rubies/ruby-2.0.0-p643/bin/ruby -I/home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/lib:/home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/rspec-support-3.3.0/lib /home/dallinb/.rvm/gems/ruby-2.0.0-p643/gems/rspec-core-3.3.2/exe/rspec spec/acceptance --color failed
```

**Comment by dallinb** [comment]
```
cassandra class
  Initial install.
localhost $ scp /tmp/beaker20150820-19457-lp1ws0 ubuntu-server-1204-x64:/tmp/apply_manifest.pp.EGHVJS {:ignore => }
    should work with no errors
  Idempotency test.
localhost $ scp /tmp/beaker20150820-19457-fp4gbg ubuntu-server-1204-x64:/tmp/apply_manifest.pp.Whf3i7 {:ignore => }
    should work with no errors (FAILED - 1)
  Service "cassandra"
    should be running
    should be enabled
  Service "datastax-agent"
    should be running
    should be enabled
  Service "opscenterd"
    should be running
    should be enabled

Failures:

  1) cassandra class Idempotency test. should work with no errors
     Failure/Error: expect(apply_manifest(cassandra_pp, :catch_failures => true).exit_code).to be_zero
       expected `2.zero?` to return true, got false
       
     # ./spec/acceptance/cassandra_spec.rb:27:in `block (3 levels) in <top (required)>'

Finished in 4 minutes 26.8 seconds (files took 2 minutes 47.5 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/acceptance/cassandra_spec.rb:26 # cassandra class Idempotency test. should work with no errors
```

**Comment by dallinb** [comment]
The commit comment for 6fd16ecfd85c99e4ccf1008ec3e5f917b1c530f6 incorrectly referred to incident 75 it in fact fixed this issue.
